/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Devuelve el estado del servicio (liveness).
         *
         *     `Settings` se recibe por inyección de dependencias (DIP), no resolviéndola dentro del
         *     handler: así es sustituible en test vía `app.dependency_overrides` (BP-3).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Peticiones HTTP + salud de la cola OCR, en formato de texto Prometheus.
         */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Tenant
         * @description Datos públicos del tenant resuelto por el subdominio, incluido su branding (S1.2/S4.2).
         *
         *     404 neutro si el host no corresponde a un tenant activo (inexistente, suspendido o no-tenant):
         *     la respuesta es idéntica en todos esos casos, no se revela qué tenants existen (lo da
         *     `public_tenant_context`, mismo portero que el registro público, S1.4).
         */
        get: operations["current_tenant_api_v1_tenants_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Manifest
         * @description Web App Manifest del tenant resuelto por el subdominio (S4.3).
         *
         *     Mismo portero público que `/tenants/current` (404 neutro sin tenant). `Content-Type:
         *     application/manifest+json`, el tipo correcto para un manifest (no `application/json`).
         */
        get: operations["tenant_manifest_api_v1_manifest_webmanifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Autentica email + contraseña (+ TOTP si aplica): access token + cookie de refresh.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rota el refresh de la cookie: nuevo access + nueva cookie; el anterior queda invalidado.
         *
         *     Sin cookie se trata igual que una cookie inválida (S5.1 C7): cuenta para el rate-limit por IP
         *     en vez de responder 401 sin más, para que machacar el endpoint sin cookie tampoco sea gratis.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoca la familia del refresh y borra la cookie. Idempotente sin cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate
         * @description Fija la contraseña y genera el secreto TOTP; devuelve la URI `otpauth://` para el QR.
         */
        post: operations["activate_api_v1_auth_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Confirm
         * @description Confirma el TOTP: enrola el segundo factor y consume el token de activación (un solo uso).
         *
         *     Rate-limit por token (S5.1 C3/C5): un código incorrecto repetido contra el MISMO token da 429
         *     tras agotar el tope, sin afectar a la activación de otro usuario en curso.
         */
        post: operations["activate_confirm_api_v1_auth_activate_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Testigo protegido: la identidad del token, leída bajo el contexto del tenant (RLS) o, para
         *     un `platform_admin`, sin tenant (hotfix S4.10 — antes daba 401 siempre para ese rol).
         *
         *     Incluye `company` (id y nombre) para un `user` acotado a su empresa; `null` para un
         *     `tenant_admin` (contexto de asesoría, ve todo el tenant) o un `platform_admin`. Ver spec S1.6
         *     (C5/C6).
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Alta autoservicio en el subdominio. CIF/contraseña inválidos -> 422; tope por IP -> 429.
         *
         *     Respuesta **genérica e idéntica** exista o no ya el email (anti-enumeración): un email duplicado
         *     no crea nada pero responde igual que un alta correcta.
         */
        post: operations["register_api_v1_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Registrations
         * @description Lista los registros pendientes de la asesoría (solo `tenant_admin`; la RLS acota).
         */
        get: operations["list_registrations_api_v1_registrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registrations/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Registration
         * @description Aprueba un registro: activa usuario + empresa. Idempotente; de otro tenant -> 404.
         */
        post: operations["approve_registration_api_v1_registrations__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registrations/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Registration
         * @description Rechaza un registro pendiente: borra el usuario y su empresa huérfana. Otro tenant -> 404.
         */
        post: operations["reject_registration_api_v1_registrations__user_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Lista las empresas de la asesoría (solo `tenant_admin`; la RLS acota lo visible).
         */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        /**
         * Create Company
         * @description Da de alta una empresa `active`. CIF inválido -> 422; CIF ya existente -> 409.
         */
        post: operations["create_company_api_v1_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Company
         * @description Borra una empresa sin dependencias. Con usuarios -> 409; de otro tenant -> 404.
         */
        delete: operations["delete_company_api_v1_companies__company_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Company
         * @description Edita una empresa. CIF inválido -> 422; CIF duplicado -> 409; de otro tenant -> 404.
         */
        patch: operations["update_company_api_v1_companies__company_id__patch"];
        trace?: never;
    };
    "/api/v1/companies/{company_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company History
         * @description Historial de ediciones de una empresa, más reciente primero. De otro tenant -> 404.
         */
        get: operations["company_history_api_v1_companies__company_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Companies
         * @description Importa un `.xlsx` (multipart `file`). Fichero/columnas inválidos -> 400 controlado.
         *
         *     Guardarraíles anti-DoS por memoria (fichero compartido por todas las asesorías): se rechaza con
         *     413 el fichero que supera `companies_import_max_bytes` ANTES de parsearlo (lectura acotada, sin
         *     materializar un `.xlsx` gigante o zip-bomb en memoria), y el parseo corta a
         *     `companies_import_max_rows` filas.
         */
        post: operations["import_companies_api_v1_companies_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Sube un fichero de factura a una empresa. Ver spec S2.1 para los códigos (201/4xx/503).
         *
         *     Orden: pertenencia (403/404) -> tamaño (413) -> el servicio hace el resto (415/422/409/503/201).
         */
        post: operations["upload_file_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{file_id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Url
         * @description URL firmada (5 min) para descargar un fichero de intake. Ver spec S2.7 para los códigos.
         *
         *     Autorización idéntica a `review`/`confirm` (S2.5): 403 empresa hermana del propio tenant, 404
         *     otro tenant/inexistente. La descarga no depende del estado del fichero (spec S2.7 §5).
         */
        get: operations["download_url_api_v1_uploads__file_id__download_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{file_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Image
         * @description Bytes reales del fichero de intake (2026-08-01), vía la API — no una redirección a MinIO.
         *
         *     Reemplaza a `download-url` como camino real del botón "Ver" del panel: MinIO nunca se expone
         *     públicamente en este proyecto, así que una URL firmada de MinIO es inalcanzable desde el
         *     navegador del usuario en el despliegue real (ver docstring de `service.get_download_bytes`).
         *     Misma autorización que `download-url` (403/404).
         */
        get: operations["download_image_api_v1_uploads__file_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{file_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Upload
         * @description Datos de revisión de un fichero ya leído (S2.4). 200 con datos; 403/404/409 por acceso.
         */
        get: operations["review_upload_api_v1_uploads__file_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{file_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Upload
         * @description Confirma un fichero y persiste su factura (S2.5). 201 con el id; 4xx según las guardas.
         */
        post: operations["confirm_upload_api_v1_uploads__file_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice History
         * @description Facturas confirmadas de los últimos 7 días del contexto del usuario (S2.6). Solo lectura.
         */
        get: operations["invoice_history_api_v1_invoices_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Invoice
         * @description Edita los campos presentes en el body de una factura confirmada. Solo `tenant_admin` (S3.3).
         *
         *     Patch parcial real: solo las claves que el cliente envió (`model_fields_set`) llegan al
         *     servicio; un campo ausente en el body conserva su valor actual (spec §2). `tax_lines: null`
         *     explícito se trata como AUSENTE (no toca los tramos): solo una lista real (incluida `[]`, que
         *     los borra todos) es una instrucción de cambio; un `null` no es una lista de tramos válida.
         */
        patch: operations["edit_invoice_api_v1_invoices__invoice_id__patch"];
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Edit History
         * @description Historial de ediciones de una factura, más reciente primero. De otro tenant -> 404.
         */
        get: operations["invoice_edit_history_api_v1_invoices__invoice_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/test/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Test Invoices
         * @description Borra TODAS las facturas de prueba de la asesoría de una vez (S3.5). Solo `tenant_admin`.
         */
        post: operations["purge_test_invoices_api_v1_invoices_test_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reporting/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Empresas de la asesoría con sus contadores agregados (S3.4). Ver spec S3.4.
         */
        get: operations["list_companies_api_v1_reporting_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reporting/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description Facturas confirmadas de la asesoría, filtradas y paginadas (S3.1). Ver spec S3.1.
         *
         *     `counterparty_tax_id` filtra por CIF EXACTO de contraparte (S5.2 C5): ya no admite texto libre
         *     por nombre (el nombre vive cifrado sin índice ciego desde S5.2, decisión de Julio).
         */
        get: operations["list_invoices_api_v1_reporting_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reporting/invoices/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Invoices
         * @description Excel con todas las facturas que casan los filtros, sin paginar (S3.2). Ver spec S3.2.
         *
         *     Mismos filtros que `list_invoices`; no acepta `cursor` (el export no pagina, spec §5).
         */
        get: operations["export_invoices_api_v1_reporting_invoices_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Logo
         * @description Sube una imagen de logo (jpeg/png, máx. 2 MiB) y devuelve su URL pública.
         *
         *     Antes de esto, `logo_url` solo admitía pegar una URL ya alojada en otro sitio. Mismo orden de
         *     validación que el intake de facturas (S2.1): vacío -> tamaño -> tipo real -> antivirus ->
         *     almacenar (spec, ver `logo_upload.upload_logo`).
         */
        post: operations["upload_logo_api_v1_platform_tenants_logo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenants
         * @description Todos los tenants, más reciente primero (S4.1).
         */
        get: operations["list_tenants_api_v1_platform_tenants_get"];
        put?: never;
        /**
         * Create Tenant
         * @description Da de alta un tenant operativo (S4.1). Slug/color inválidos -> 422; slug duplicado -> 409.
         */
        post: operations["create_tenant_api_v1_platform_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Metrics
         * @description Consumo agregado de todos los tenants, ordenado por slug (S4.5).
         */
        get: operations["tenant_metrics_api_v1_platform_tenants_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/convert-to-production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert To Production
         * @description Pone `is_demo=false` (S4.4). Idempotente si ya era producción; id inexistente -> 404.
         */
        post: operations["convert_to_production_api_v1_platform_tenants__tenant_id__convert_to_production_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Demo Tenant
         * @description Borra un tenant demo por completo (S4.4). Id inexistente -> 404; no es demo -> 409.
         */
        post: operations["purge_demo_tenant_api_v1_platform_tenants__tenant_id__purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/custom-domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Custom Domain
         * @description Asigna o quita (`null`) el dominio propio de un tenant (S4.6, alcance acotado — ver spec
         *     §0). Formato inválido -> 422; id inexistente -> 404; duplicado -> 409.
         */
        patch: operations["set_custom_domain_api_v1_platform_tenants__tenant_id__custom_domain_patch"];
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend Tenant
         * @description Bloquea el login de todos los usuarios del tenant, sin tocar datos (S4.7). Idempotente si
         *     ya estaba suspendido; id inexistente -> 404.
         */
        post: operations["suspend_tenant_api_v1_platform_tenants__tenant_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate Tenant
         * @description Revierte `suspend` (S4.7). Idempotente si ya estaba activo; id inexistente -> 404.
         */
        post: operations["reactivate_tenant_api_v1_platform_tenants__tenant_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Tenant
         * @description Genera un ZIP completo (BD + ficheros) del tenant y devuelve una URL de descarga firmada
         *     (S4.7). Id inexistente -> 404.
         */
        post: operations["export_tenant_api_v1_platform_tenants__tenant_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Tenant
         * @description Borra un tenant entero (S4.7, alcance real: no solo demo, a diferencia de `purge`). Id
         *     inexistente -> 404; `confirm_slug` no coincide -> 422; sin ningún export previo -> 409.
         */
        delete: operations["delete_tenant_api_v1_platform_tenants__tenant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_platform_settings_get"];
        /** Set Settings */
        put: operations["set_settings_api_v1_platform_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/ocr-ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ranking */
        get: operations["get_ranking_api_v1_platform_ocr_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivateConfirmRequest
         * @description Cuerpo de `POST /auth/activate/confirm`.
         */
        ActivateConfirmRequest: {
            /** Token */
            token: string;
            /** Totp Code */
            totp_code: string;
        };
        /**
         * ActivateRequest
         * @description Cuerpo de `POST /auth/activate`. La política de contraseña la valida el endpoint.
         */
        ActivateRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * ApprovalResponse
         * @description Respuesta de la aprobación de un registro.
         */
        ApprovalResponse: {
            /** Status */
            status: string;
        };
        /** Body_import_companies_api_v1_companies_import_post */
        Body_import_companies_api_v1_companies_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_api_v1_uploads_post */
        Body_upload_file_api_v1_uploads_post: {
            /** File */
            file: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
        };
        /** Body_upload_logo_api_v1_platform_tenants_logo_post */
        Body_upload_logo_api_v1_platform_tenants_logo_post: {
            /** File */
            file: string;
        };
        /**
         * CompanyCreate
         * @description Cuerpo de `POST /companies`.
         */
        CompanyCreate: {
            /** Name */
            name: string;
            /** Cif */
            cif: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CompanyEditOut
         * @description Una fila del historial de ediciones de una empresa (2026-08-01).
         */
        CompanyEditOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Field */
            field: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            /**
             * Edited By
             * Format: uuid
             */
            edited_by: string;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
        };
        /**
         * CompanyOut
         * @description Empresa en la respuesta (alta, edición y listado).
         */
        CompanyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Cif */
            cif: string;
            /** Status */
            status: string;
        };
        /**
         * CompanyRowOut
         * @description Una fila de la ficha agregada de empresas (S3.4, spec §2/§3 C1).
         */
        CompanyRowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Cif */
            cif: string;
            /** Status */
            status: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Count */
            user_count: number;
            /** Invoice Count */
            invoice_count: number;
            /** Last Invoice At */
            last_invoice_at: string | null;
        };
        /**
         * CompanyUpdate
         * @description Cuerpo de `PATCH /companies/{id}` (patch parcial: solo los campos presentes cambian).
         */
        CompanyUpdate: {
            /** Name */
            name?: string | null;
            /** Cif */
            cif?: string | null;
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: ("active" | "pending") | null;
        };
        /**
         * ConfirmIn
         * @description Cuerpo de la confirmación (S2.5): datos confirmados por el humano.
         */
        ConfirmIn: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "recibida" | "emitida";
            /** Issue Date */
            issue_date?: string | null;
            /** Counterparty Tax Id */
            counterparty_tax_id?: string | null;
            /** Counterparty Name */
            counterparty_name?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Net Amount */
            net_amount?: number | string | null;
            /** Tax Amount */
            tax_amount?: number | string | null;
            /** Total Amount */
            total_amount?: number | string | null;
            /** Irpf Amount */
            irpf_amount?: number | string | null;
            /**
             * Tax Lines
             * @default []
             */
            tax_lines: components["schemas"]["TaxLineIn"][];
            /**
             * Responsibility Accepted
             * @default false
             */
            responsibility_accepted: boolean;
            /**
             * Is Test
             * @default false
             */
            is_test: boolean;
        };
        /**
         * CustomDomainIn
         * @description Cuerpo de `PATCH /platform/tenants/{tenant_id}/custom-domain` (S4.6). `None` lo quita.
         */
        CustomDomainIn: {
            /** Custom Domain */
            custom_domain?: string | null;
        };
        /**
         * DeleteTenantIn
         * @description Cuerpo de `DELETE /platform/tenants/{tenant_id}` (S4.7): segundo factor de confirmación
         *     verificado en servidor, spec §3 decisión 4.
         */
        DeleteTenantIn: {
            /** Confirm Slug */
            confirm_slug: string;
        };
        /**
         * DownloadUrlOut
         * @description URL firmada de descarga de un fichero (respuesta 200, S2.7).
         */
        DownloadUrlOut: {
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * DuplicateRowOut
         * @description Fila omitida por CIF ya existente en el informe: número de fila (1-based) y CIF.
         */
        DuplicateRowOut: {
            /** Row */
            row: number;
            /** Cif */
            cif: string;
        };
        /** EngineRankingOut */
        EngineRankingOut: {
            /** Engine */
            engine: string;
            /** Invoices Read */
            invoices_read: number;
            /** Average Score */
            average_score: number;
            /** First Place Count */
            first_place_count: number;
        };
        /**
         * ExportOut
         * @description Respuesta de `POST /platform/tenants/{tenant_id}/export` (S4.7).
         */
        ExportOut: {
            /** Download Url */
            download_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Respuesta del healthcheck.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /**
         * HistoryEntryOut
         * @description Una entrada del historial de facturas confirmadas (S2.6, spec §2).
         */
        HistoryEntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Date */
            issue_date: string | null;
            /** Direction */
            direction: string;
            /** Counterparty Tax Id */
            counterparty_tax_id: string | null;
            /** Counterparty Name */
            counterparty_name: string | null;
            /** Counterparty Cif Status */
            counterparty_cif_status: string;
            /** Total Amount */
            total_amount: string | null;
            /**
             * Confirmed At
             * Format: date-time
             */
            confirmed_at: string;
        };
        /**
         * HistoryOut
         * @description Respuesta de `GET /invoices/history`: lista, más reciente primero (spec §2/§3).
         */
        HistoryOut: {
            /** Entries */
            entries: components["schemas"]["HistoryEntryOut"][];
        };
        /**
         * ImportReportOut
         * @description Informe de la importación del Excel.
         */
        ImportReportOut: {
            /** Created */
            created: number;
            /** Invalid */
            invalid: components["schemas"]["InvalidRowOut"][];
            /** Duplicates */
            duplicates: components["schemas"]["DuplicateRowOut"][];
            /** Truncated */
            truncated: boolean;
        };
        /**
         * InvalidRowOut
         * @description Fila rechazada en el informe de importación: número de fila (1-based) y motivo.
         */
        InvalidRowOut: {
            /** Row */
            row: number;
            /** Reason */
            reason: string;
        };
        /**
         * InvoiceEditEntryOut
         * @description Una fila del historial de ediciones de una factura (2026-08-01).
         */
        InvoiceEditEntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Field */
            field: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            /**
             * Edited By
             * Format: uuid
             */
            edited_by: string;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
        };
        /**
         * InvoiceEditIn
         * @description Cuerpo de `PATCH /invoices/{id}` (S3.3): patch parcial, solo cambian los campos presentes.
         */
        InvoiceEditIn: {
            /** Issue Date */
            issue_date?: string | null;
            /** Counterparty Tax Id */
            counterparty_tax_id?: string | null;
            /** Counterparty Name */
            counterparty_name?: string | null;
            /** Net Amount */
            net_amount?: number | string | null;
            /** Tax Amount */
            tax_amount?: number | string | null;
            /** Total Amount */
            total_amount?: number | string | null;
            /** Irpf Amount */
            irpf_amount?: number | string | null;
            /** Tax Lines */
            tax_lines?: components["schemas"]["TaxLineIn"][] | null;
        };
        /**
         * InvoiceOut
         * @description Estado de la factura tras la edición (spec S3.3 §2).
         */
        InvoiceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Date */
            issue_date: string | null;
            /** Counterparty Tax Id */
            counterparty_tax_id: string | null;
            /** Counterparty Name */
            counterparty_name: string | null;
            /** Counterparty Cif Status */
            counterparty_cif_status: string;
            /** Net Amount */
            net_amount: string | null;
            /** Tax Amount */
            tax_amount: string | null;
            /** Total Amount */
            total_amount: string | null;
            /** Irpf Amount */
            irpf_amount: string | null;
            /** Balance Ok */
            balance_ok: boolean | null;
        };
        /**
         * InvoiceRowOut
         * @description Una fila del panel de facturas (spec §2/§3 C8).
         */
        InvoiceRowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Cif */
            company_cif: string;
            /** Issue Date */
            issue_date: string | null;
            /** Direction */
            direction: string;
            /** Counterparty Tax Id */
            counterparty_tax_id: string | null;
            /** Counterparty Name */
            counterparty_name: string | null;
            /** Counterparty Cif Status */
            counterparty_cif_status: string;
            /** Net Amount */
            net_amount: string | null;
            /** Tax Amount */
            tax_amount: string | null;
            /** Total Amount */
            total_amount: string | null;
            /** Irpf Amount */
            irpf_amount: string | null;
            /** Tax Lines */
            tax_lines: components["schemas"]["TaxLineOut"][];
            /**
             * Confirmed At
             * Format: date-time
             */
            confirmed_at: string;
            /**
             * Confirmed By
             * Format: uuid
             */
            confirmed_by: string;
            /**
             * Uploaded File Id
             * Format: uuid
             */
            uploaded_file_id: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * LoginRequest
         * @description Cuerpo de `POST /auth/login`.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /**
         * LogoUploadOut
         * @description Respuesta de `POST /platform/tenants/logo`: la URL pública lista para usar como `logo_url`
         *     en el alta/edición de un tenant (2026-08-01, decisión de Julio).
         */
        LogoUploadOut: {
            /** Logo Url */
            logo_url: string;
        };
        /**
         * MeCompanyOut
         * @description Empresa a la que está acotado un `user` en `/auth/me` (`null` para `tenant_admin`).
         */
        MeCompanyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * MeOut
         * @description Respuesta de `GET /auth/me` (S1.6 C5/C6), tipada para que el cliente autogenerado la use
         *     sin `unknown` (S3.5: la necesita el frontend para saber el rol del usuario autenticado).
         *
         *     `tenant`/`company` son `null` para un `platform_admin` (sin tenant, hotfix S4.10) además del
         *     caso ya existente de `company=null` para un `tenant_admin`. `is_admin_tech` (S4.10): siempre
         *     `False` salvo para un `platform_admin` con el flag activado (nunca desde la aplicación).
         */
        MeOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant */
            tenant: string | null;
            company: components["schemas"]["MeCompanyOut"] | null;
            /** Is Admin Tech */
            is_admin_tech: boolean;
        };
        /**
         * PanelOut
         * @description Respuesta de `GET /reporting/invoices`: una página del panel (spec §2).
         */
        PanelOut: {
            /** Items */
            items: components["schemas"]["InvoiceRowOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PlatformSettingsIn */
        PlatformSettingsIn: {
            /** Ocr Experiment Enabled */
            ocr_experiment_enabled: boolean;
        };
        /** PlatformSettingsOut */
        PlatformSettingsOut: {
            /** Ocr Experiment Enabled */
            ocr_experiment_enabled: boolean;
        };
        /**
         * PurgeResultOut
         * @description Respuesta de `POST /invoices/test/purge` (S3.5): cuántas facturas de prueba se borraron.
         */
        PurgeResultOut: {
            /** Purged */
            purged: number;
        };
        /**
         * RegisterRequest
         * @description Cuerpo de `POST /register`.
         */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Company Name */
            company_name: string;
            /** Cif */
            cif: string;
            /** Password */
            password: string;
        };
        /**
         * RegisterResponse
         * @description Respuesta genérica del registro (idéntica exista o no el email: anti-enumeración).
         */
        RegisterResponse: {
            /** Status */
            status: string;
        };
        /**
         * RegistrationOut
         * @description Un registro pendiente en el listado del admin (email + empresa + señal de unión a existente).
         *
         *     `joins_existing_company` avisa a la pantalla de aprobación de que el CIF casaba con una empresa
         *     ya activa (el usuario se une a ella, no crea empresa nueva): defensa ante secuestro por CIF.
         */
        RegistrationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Company */
            company: string | null;
            /** Joins Existing Company */
            joins_existing_company: boolean;
        };
        /**
         * TaxLineIn
         * @description Un tramo de IVA confirmado del body de `confirm`.
         */
        TaxLineIn: {
            /** Iva Pct */
            iva_pct?: number | string | null;
            /** Base */
            base?: number | string | null;
            /** Cuota */
            cuota?: number | string | null;
        };
        /**
         * TaxLineOut
         * @description Un tramo de IVA de la fila del panel.
         */
        TaxLineOut: {
            /** Iva Pct */
            iva_pct: string | null;
            /** Base */
            base: string | null;
            /** Cuota */
            cuota: string | null;
        };
        /**
         * TenantCreateIn
         * @description Cuerpo de `POST /platform/tenants` (spec S4.1 §2/§3, `is_demo` desde S4.4).
         */
        TenantCreateIn: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Color Primary */
            color_primary?: string | null;
            /** Color Secondary */
            color_secondary?: string | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /**
         * TenantCurrentOut
         * @description Respuesta de `GET /tenants/current` (S1.2 + branding S4.2).
         *
         *     Los campos de branding son `null` cuando el tenant no tiene fila en `tenant_branding` o el campo
         *     concreto está vacío: el servidor nunca inventa un valor por defecto (spec S4.2 decisión 1); los
         *     valores de reemplazo ("Setex tal cual hoy") los aplica el frontend.
         */
        TenantCurrentOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Is Demo */
            is_demo: boolean;
            /** Logo Url */
            logo_url: string | null;
            /** Color Primary */
            color_primary: string | null;
            /** Color Secondary */
            color_secondary: string | null;
            /** App Name */
            app_name: string | null;
            /** Favicon */
            favicon: string | null;
        };
        /**
         * TenantMetricsOut
         * @description Consumo agregado de un tenant (S4.5). `ocr_extractions_count` es un proxy de uso, nunca una
         *     cifra monetaria (spec §0 decisión 1: no hay coste real en € disponible hoy).
         */
        TenantMetricsOut: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Companies Count */
            companies_count: number;
            /** Admins Count */
            admins_count: number;
            /** Users Count */
            users_count: number;
            /** Invoices This Month */
            invoices_this_month: number;
            /** Invoices Total Count */
            invoices_total_count: number;
            /** Ocr Extractions Count */
            ocr_extractions_count: number;
            /** Last Activity At */
            last_activity_at: string | null;
        };
        /**
         * TenantOut
         * @description Un tenant en la respuesta (alta/listado/conversión a producción). `custom_domain` (S4.6)
         *     solo `POST /platform/tenants` (alta) lo devuelve siempre `None`: un tenant recién creado
         *     nunca tuvo tiempo de que se le asignara uno (spec §3 decisión 3).
         */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Custom Domain */
            custom_domain?: string | null;
        };
        /**
         * UploadOut
         * @description Fichero de intake creado (respuesta 201).
         */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Scan Status */
            scan_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    current_tenant_api_v1_tenants_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCurrentOut"];
                };
            };
        };
    };
    tenant_manifest_api_v1_manifest_webmanifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    activate_api_v1_auth_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_confirm_api_v1_auth_activate_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    register_api_v1_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_registrations_api_v1_registrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOut"][];
                };
            };
        };
    };
    approve_registration_api_v1_registrations__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_registration_api_v1_registrations__user_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
        };
    };
    create_company_api_v1_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_api_v1_companies__company_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_v1_companies__company_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_history_api_v1_companies__company_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyEditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_companies_api_v1_companies_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_companies_api_v1_companies_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_url_api_v1_uploads__file_id__download_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_api_v1_uploads__file_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_upload_api_v1_uploads__file_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_upload_api_v1_uploads__file_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_history_api_v1_invoices_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
        };
    };
    edit_invoice_api_v1_invoices__invoice_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceEditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_edit_history_api_v1_invoices__invoice_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceEditEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_test_invoices_api_v1_invoices_test_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResultOut"];
                };
            };
        };
    };
    list_companies_api_v1_reporting_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRowOut"][];
                };
            };
        };
    };
    list_invoices_api_v1_reporting_invoices_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                counterparty_tax_id?: string | null;
                confirmed_by?: string | null;
                cif_status?: string | null;
                company_id?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_invoices_api_v1_reporting_invoices_export_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                counterparty_tax_id?: string | null;
                confirmed_by?: string | null;
                cif_status?: string | null;
                company_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_logo_api_v1_platform_tenants_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_v1_platform_tenants_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_api_v1_platform_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
        };
    };
    create_tenant_api_v1_platform_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_metrics_api_v1_platform_tenants_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantMetricsOut"][];
                };
            };
        };
    };
    convert_to_production_api_v1_platform_tenants__tenant_id__convert_to_production_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_demo_tenant_api_v1_platform_tenants__tenant_id__purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_custom_domain_api_v1_platform_tenants__tenant_id__custom_domain_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomDomainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_tenant_api_v1_platform_tenants__tenant_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_tenant_api_v1_platform_tenants__tenant_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_tenant_api_v1_platform_tenants__tenant_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tenant_api_v1_platform_tenants__tenant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTenantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_platform_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSettingsOut"];
                };
            };
        };
    };
    set_settings_api_v1_platform_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ranking_api_v1_platform_ocr_ranking_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineRankingOut"][];
                };
            };
        };
    };
}
